greeting.js

* Hello, 안녕하세요, hola 중 한 개를 골라 
랜덤으로 사용자에게 인사하도록 greeting.js를 변경하였습니다.
* 랜덤한 인사 대답을 위해 Math.random()보다 더 나은 방법이 있을까요?

인사하기 코드 구현

---

index.js
lunch.js
package-lock.json
package.json

#15 진수원 중식 식단 안내
"오늘 점심 뭐야"라고 봇에게 물으면 오늘의 진수원 점심을 대답해준다.
메뉴는 진수원 페이지에서 크롤링해온다.
```
npm install axios
npm install cheerio
```
axios와 cheerio를 설치해서 파일 내용 변경됨
두가지 설치해야 lunch.js 작동가능함
'오늘 점심 뭐야'라고 명령이 들어오면 lunch.js를 실행시킴
학교 식단 페이지(https://sobi.chonbuk.ac.kr/menu/week_menu.php) 에서 진수원 점심 메뉴를 크롤링 해옴
하드코딩 된 부분(selector에서 메뉴 반환하는 부분, 메뉴를 출력하는 부분)이 있어 리팩토링 필요해 보임

feat: add answer the today lunch(#15)

---

greeting.js
lunch.js

```lunchScore < 1```에서 ```lunchScore <= 1```으로,
```lunchScore > 3```에서 ```lunchScore >= 3```으로 변경하였습니다.

점심 메뉴 평가 코드 수정 

---

greeting.js
lunch.js
square.js
test.spec.js

lunch.js, square.js가 mocha test를 할 수 있도록 해주었습니다.
<br>
<br>
- lunch.js, square.js의 mocha test를 위해 lunch.js, square.js, test.spec.js를 변경하였습니다.
- lunch.js, square.js, greeting.js의 console 출력 형식을 맞춰주었습니다.
<br>
<br>

test(#44): mocha test for lunch.js and square.js

---

README.md

ReadMe 파일 수정하였습니다.
<br>
<br>
ReadMe 파일에 현재 봇 기능, starting for user, starting for developer 추가 하였습니다.
<br>
ReadMe에 더 추가할 사항이 있을까요?
<br>

fix #16 Update README.md

---

package.json

script에 start, test 작성해 npm start, npm test 명령 작동합니다.
<br>
<br>
script에 start, test 작성했습니다.
npm start명령시 node index.js 명령을 수행합니다.
npm test 명령시 mocha test.spec.js --timeout 10000 명령을 수행합니다.
<br>

Chore/53 fix #53 package.json 수정

---

index.js
weeklunch.js

css 선택자 undefined 버그 수정 및 weeklunch.js 파일 추가
<br>
<br>
index.js에서 챗봇에게 '이번주 뭐 나와'라고 물으면 weeklunch.js에 따라 대답하도록 설정
lunch.js에서 이번주 메뉴 불러오지 못하던 버그 수정. css 선택자의 범위를 완화하여 넓은 범위에서 원하는 선택자를 찾을 수 있도록 설정함. 앞으로 에러 안날거에요😊
weeklunch.js에서 이번주 메뉴를 불러와 MonMenu, TueMenu, WedMenu, ThuMenu, FriMenu로 불러오도록 설정.
<br>
weeklunch.js와 lunch.js 코드가 겹치는 부분이 많은데 모듈로 만들어 사용할 방법이 있으면 좋겠어요.
<br>

bug(#65): fix menu bug and add weekMenu arr

---

.github/workflows/release.yml

release(#2.0.1): release test

---

department.js
findDepartment.py
index.js

levenshtein 알고리즘을 이용해 학과 이름을 검색할 수 있게 함
<br>
<br>
index.js는 사용자 명령어만 수정했습니다.
department.js에서 학과를 검색하는 부분을 지웠습니다. 무조건 findDepartment.py를 호출하고 해당 파일 안에서 검사합니다. 입력받은 값이 dictionary의 key값 중 하나와 일치한다면 과의 위치를 출력해주고 끝나고, 없으면 levenshtein 알고리즘이 실행됩니다.
<br>
알고리즘 자체가 정교한 것은 아닌 것 같아요. korean language and라고 쳤을 때 Urban Engineering이 나오더라구요. 그런데 Urban Engineering이 가장 숫자가 작은 값이 맞아요.. 이건 과제 수행과는 관계 없겠죠?
<br>

feat(#50): add find levenshtein and closed #50

---

.husky/pre-commit
package.json

lint-staged가 이상하게 작동하여 수정
<br>
<br>
[현재 진행중인 lint-staged git 페이지](https://github.com/okonet/lint-staged/pull/1163)
무려 현재 에러 발생중인 lint-staged 문제였습니다. exec >/dev/tty 2>&1 명령어를 추가해주지 않아도 린트 작업에는 문제가 없으나 미관상 좋지 않기도 해서 추가했습니다.
<br>
<br>
원래 화면
변경된 화면

feat(#69): edit pre-commit

---

.github/workflows/mocha_test.yml
department.js
test_spec/test_department.js
test_spec/test_greeting.js
test_spec/test_lunch.js
test_spec/test_square.js
test_spec/test_weeklunch.js

그 전 pr에서 comment 받은 수정 사항을 반영하였습니다.
<br>
<br>
```npm ci``` ```npm install mocha -g```를 모듈화 하였습니다.
greeting.js 모카 테스트 시, 값이 돌아오는 지만 확인하도록 하였습니다.
* 제가 test/52 브랜치를 실수로 삭제하여 어제 올린 test/52 PR이 모두 날라갔습니다.. 그래서 다시 PR올립니다. 
<br>
<br>

test(#52) mocha test 수정 사항 반영

---

.github/workflows/deploy.yml

feat(#88): make deploy.yml

---

.github/workflows/deploy.yml

문법 잘못된 부분 고침
<br>
<br>
<br>
<br>

feat(#88): edit deploy.yml

---

.github/workflows/deploy.yml

feat(#88): add copy source in deploy.yml

---

.github/workflows/deploy.yml

feat(#88): add remote Key

---

package.json

npm test 입력 시, test_spec/* 실행되도록 변경
<br>
<br>
mocha test를 위해 현재는 test_spec/*을 이용하지만, npm test는 test.spec.js를 실행시켰다.
test_spec/* 을 이용하도록 하기 위해 package.json을 변경하였다.
<br>
<br>

feat(#99): npm test시, 실행되는 파일 변경

---

department.js
index.js

python3 버전을 사용하도록 변경
0과 1 대신 true, false를 사용하도록 변경
<br>
<br>
<br>
<br>

style(#101): change style

---

.github/workflows/deploy.yml

deploy를 위한 git action file 작성
<br>
<br>
main에 pull_request 되면 네이버 서버로 자동배포 합니다.
1. workflow에 토큰을 생성합니다.
2. 로그인을 하고 기존에 동작중인 프로세스를 찾아 중지시킵니다. (pkill)
3. workflow의 코드를 서버로 복사합니다.
4. 의존성 설치 후 npm start를 백그라운드로 실행하고 액션을 종료합니다.
<br>
현재 사용 중인 봇을 메인 봇으로 정하게 되니 로컬에서 사용할 때랑 토큰이 겹칩니다. 봇을 2개 만들어야 할 것 같아요.
<br>

feat(#88): add deploy.yml

---

README.md
department.js

변경된 사항들에 대해 readme 수정 완료 했습니다.
<br>
<br>
<br>
<br>

doc(#101): readme 수정 완료

---

.github/workflows/mocha_test.yml

mocha test를 모든 js파일에 대해 진행하도록 하는 대신 기능 관련 js파일만 실행하도록 수정
<br>
<br>
모든 js파일에 대해 mocha test를 진행하려던 전과 달리 
현재는 ```greeting.js``` ```square.js``` ```lunch.js``` ```weeklunch.js``` ```department.js```에 대해서만 모카테스트 진행
<br>
<br>

chore(#109): mocha test 실행 파일 수정

---

.github/workflows/deploy.yml

토큰 이름이 맞지 않아 실행이 안되는 부분 수정
<br>
<br>
<br>
<br>

hotfix(#88): token name issue

---

department.js
greeting.js
index.js
lunch.js
square.js
weeklunch.js

사용자 입력 메시지, 봇이 보낸 메시지도 로그에 기록하도록 수정
<br>
<br>
전에는 console.log(); 되는 것들만 로그에 기록되었지만,
사용자가 입력한 메시지, 봇이 보낸 메시지도 로그에 기록되도록 수정하였다.
<br>
<br>

refactor(#111): 로그가 기록 해야 할 내용 추가
